name: Execute Puppeteer Script and Generate Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for Puppeteer and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            subversion \
            git \
            sudo \
            ripgrep \
            python3 \
            python3-venv \
            gnupg2 \
            libnss3 \
            libxss1 \
            libx11-xcb1 \
            libxcomposite1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libnspr4 \
            libxrandr2 \
            libxshmfence1 \
            libgtk-3-0 \
            fonts-liberation \
            libappindicator3-1 \
            libx11-dev \
            libxrender-dev

      - name: Clone repository
        run: git clone https://github.com/d4rk5id3r/plugins_downloader

      - name: Sleep for 10 Seconds
        run: sleep 10

      - name: Create Python virtual environment and install dependencies
        run: |
          cd plugins_downloader && pwd && pip install beautifulsoup4 && pip install requests && ls -la && sudo apt-get install ripgrep -y && chmod +x single_grep.sh && ls -la && python3 extractor.py && ls -la && \
          # Provide user input for single_grep.sh using echo
          echo -e "12" | ./single_grep.sh  # Replace 1, 2, 3 with the actual integer inputs expected by your script

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: /home/runner/work/extractor/extractor/plugins_downloader/report_line_12.txt



      - name: Remove all Plugin file after Extraction and Grepping
        run: |
          rm -rf extracted_plugins/*  && ls && pwd

        
      - name: run on line 2
        run: |
         cd plugins_downloader && pwd && python3 extractor.py && ls -la && \
         # Provide user input for single_grep1.sh using echo
         echo -e "12" | ./single_grep.sh  # Replace 1, 2, 3 with the actual integer inputs expected by your script


      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: /home/runner/work/extractor/extractor/plugins_downloader/report_line_12.txt
